kind: pipeline
type: docker
name: build

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - push
  - pull_request

steps:
- name: build
  image: golang:1.23
  volumes:
  - name: deps
    path: /go
  commands:
  - go get ./...
  - go build cmd/identity/main.go

- name: test
  image: golang:1.23
  volumes:
  - name: deps
    path: /go
  commands:
  - go test -v ./...

volumes:
- name: deps
  temp: {}

services:
- name: nats
  image: nats:2.10.18-alpine
  command:
  - --jetstream

---
kind: pipeline
type: docker
name: release-linux-amd64

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - tag

steps:
- name: build
  image: golang:1.23-alpine
  commands:
  - apk add gcc musl-dev
  - go build -ldflags "-X main.Version=${DRONE_TAG}
                       -X main.BuildTime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
                       -X main.GitCommit=${DRONE_COMMIT}" 
             -o release/linux/amd64/identity cmd/identity/main.go

- name: publish
  image: plugins/docker
  settings:
    dockerfile: build/Dockerfile.linux.amd64
    repo: flarexio/identity
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD

---
kind: pipeline
type: docker
name: release-linux-arm64

platform:
  arch: arm64
  os: linux

trigger:
  event:
  - tag

steps:
- name: build
  image: golang:1.23-alpine
  commands:
  - apk add gcc musl-dev
  - go build -ldflags "-X main.Version=${DRONE_TAG}
                       -X main.BuildTime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
                       -X main.GitCommit=${DRONE_COMMIT}" 
             -o release/linux/arm64/identity cmd/identity/main.go

- name: publish
  image: plugins/docker
  settings:
    dockerfile: build/Dockerfile.linux.arm64
    repo: flarexio/identity
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD
