kind: pipeline
type: docker
name: build

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - push
  - pull_request

steps:
- name: build
  image: golang:1.19
  volumes:
  - name: deps
    path: /go
  commands:
  - go get ./...
  - go build cmd/main.go

- name: test
  image: golang:1.19
  volumes:
  - name: deps
    path: /go
  commands:
  - go test -v ./...

volumes:
- name: deps
  temp: {}

services:
- name: nats
  image: nats:2.9.16-alpine
  command:
  - --jetstream

---
kind: pipeline
type: docker
name: release-linux-amd64

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - tag

steps:
- name: build
  image: golang:1.19-alpine3.17
  commands:
  - apk add gcc musl-dev
  - go build -o release/linux/amd64/identity cmd/main.go

- name: publish
  image: plugins/docker
  settings:
    dockerfile: build/Dockerfile.linux.amd64
    repo: mirror770109/identity
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD
