name: $INSTANCE_NAME

# external:
#   scheme: http
#   address: identity.mirror520.svc.cluster.local
#   port: 80

baseUrl: identity.linyc.idv.tw

jwt:
  secret: jwt_secret_key
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m

transport:
  nats:
    enabled: true
    reqPrefix: identity.$INSTANCE_NAME
  loadBalancing:
    enabled: false

persistence:
  driver: badger
  name: users

eventBus:
  provider: nats
  host: nats
  port: 4222
  users:
    stream:
      name: USERS
      config: |
        {
          "description": "identity:users",
          "subjects": [
            "users.>"
          ]
        }
    consumer:
      name: $INSTANCE_NAME
      stream: USERS
      config: |
        {
          "ack_policy": "explicit"
        }

providers:
  google:
    client: 
      id: google_client_id
      secret: google_client_secret

test:
  token: YOUR_GOOGLE_JWT_TOKEN
