name: identity-1

baseUrl: api.linyc.idv.tw

jwt:
  secret: jwt_secret_key
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m

persistent: badger

databases:
  # mysql:
  #   driver: mysql
  #   name: identity
  #   host: mysql
  #   port: 3306
  #   username: root
  #   password:
  sqlite:
    driver: sqlite
    name: identity
  badger:
    driver: badger
    name: identity
  # redis:
  #   driver: redis
  #   host: redis
  #   port: 6379
  #   name: 0

providers:
  google:
    client: 
      id: google_client_id
      secret: google_client_secret

test:
  token: YOUR_GOOGLE_JWT_TOKEN
