name: identity-1

baseUrl: api.linyc.idv.tw

jwt:
  secret: jwt_secret_key
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m

persistent:
  driver: badger
  name: users

eventBus:
  provider: nats
  host: nats
  port: 4222
  users:
    stream:
      name: USERS
      config: |
        {
          "description": "identity:users",
          "subjects": [
            "users.>"
          ]
        }
    consumer:
      name: identity-1
      stream: USERS
      config: |
        {
          "ack_policy": "explicit"
        }

providers:
  google:
    client: 
      id: google_client_id
      secret: google_client_secret

test:
  token: YOUR_GOOGLE_JWT_TOKEN
