name: $INSTANCE_NAME

baseUrl: identity.flarex.io

jwt:
  secret: jwt_secret_key # todo: change to ed25519
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m
  audiences:
  - identity.flarex.io
  - wallet.flarex.io

persistence:
  driver: badger
  name: users

eventBus:
  provider: nats
  users:
    stream:
      name: USERS
      config: |
        {
          "description": "identity:users",
          "subjects": [
            "users.>"
          ]
        }
    consumer:
      name: $INSTANCE_NAME
      stream: USERS
      config: |
        {
          "ack_policy": "explicit"
        }

providers:
  google:
    client: 
      id: google_client_id
      secret: google_client_secret
  line:
    channel:
      id: line_login_channel_id
      secret: line_login_channel_secret
    redirectURI: https://identity.flarex.io/auth/line/callback
  passkeys:
    baseURL: https://passkeys.hanko.io
    tenantID: 00000000-0000-0000-0000-000000000000
    api:
      id: 00000000-0000-0000-0000-000000000000
      secret: hanko_api_secret
    audience: wallet.flarex.io
    origins:
    - https://identity.flarex.io
    - https://wallet.flarex.io

test:
  tokens:
    google: YOUR_GOOGLE_JWT_TOKEN
    passkeys: YOUR_PASSKEYS_JWT_TOKEN
