name: $INSTANCE_NAME

baseUrl: identity.flarex.io

jwt:
  secret: jwt_secret_key
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m

transports:
  http:
    enabled: false
    internal:
      # scheme: http
      # host: identity.mirror520.svc.cluster.local
      # port: 80
      health: 
        enabled: true
        path: /health
    # external:
    #   scheme: https
    #   host: identity.flarex.io
    #   port: 443
  nats:
    enabled: false
    internal:
      scheme: nats
      host: nats
      port: 4222
    health:
      enabled: true
      path: identity.$INSTANCE_NAME.health
    external:
      scheme: nats
      host: nats.flarex.io
      port: 4222
    reqPrefix: identity.$INSTANCE_NAME
  loadBalancing:
    enabled: false

persistence:
  driver: badger
  name: users

eventBus:
  provider: nats
  users:
    stream:
      name: USERS
      config: |
        {
          "description": "identity:users",
          "subjects": [
            "users.>"
          ]
        }
    consumer:
      name: $INSTANCE_NAME
      stream: USERS
      config: |
        {
          "ack_policy": "explicit"
        }

providers:
  google:
    client: 
      id: google_client_id
      secret: google_client_secret

test:
  token: YOUR_GOOGLE_JWT_TOKEN
