name: identity-1

baseUrl: api.linyc.idv.tw

jwt:
  secret: jwt_secret_key
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m

persistent:
  driver: badger
  name: identity

transport:
  provider: nats
  host: nats
  port: 4222
  streams:
  - name: USERS
    config: |
    {
      "subjects": [
        "users.>"
      ]
    }
  consumers:
  - name: $name
    stream: USERS
    config: |
    {}

providers:
  google:
    client: 
      id: google_client_id
      secret: google_client_secret

test:
  token: YOUR_GOOGLE_JWT_TOKEN
