name: $INSTANCE_NAME

baseUrl: identity.flarex.io

jwt:
  secret: jwt_secret_key
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m

persistence:
  driver: badger
  name: users

eventBus:
  provider: nats
  users:
    stream:
      name: USERS
      config: |
        {
          "description": "identity:users",
          "subjects": [
            "users.>"
          ]
        }
    consumer:
      name: $INSTANCE_NAME
      stream: USERS
      config: |
        {
          "ack_policy": "explicit"
        }

providers:
  google:
    client: 
      id: google_client_id
      secret: google_client_secret
  passkeys:
    baseURL: https://passkeys.hanko.io
    tenantID: 00000000-0000-0000-0000-000000000000
    api:
      id: 00000000-0000-0000-0000-000000000000
      secret: hanko_api_secret
    origins:
    - https://identity.flarex.io
    - https://wallet.flarex.io

test:
  token: YOUR_GOOGLE_JWT_TOKEN
