baseurl: api.linyc.idv.tw

jwt:
  secret: jwt_secret_key
  timeout: 1h
  refresh:
    enabled: true
    maximum: 1h30m

db:
  driver: mysql
  host: mysql
  port: 3306
  username: jinte
  password: password
  dbname: jinte

redis:
  host: redis
  port: 6379
  password: 
  db: 0

google:
  client: 
    id: google_client_id
    secret: google_client_secret

services:
  edge:
    otp: 
      length: 32
      timeout: 30m
    jwt:
      secret: edge_jwt_secret
      timeout: 60m               # JWT_TIMEOUT >= OTP_TIMEOUT
